// Hello Interview question lists (hellointerview.com, researched 2026-09-28).
//
// HELLO_INTERVIEW_LIST is the research record: every system design (32) and low-level
// design (9) problem breakdown, with the difficulty from each page's own metadata and the
// Hello Interview patterns tied to it. A pattern is only listed when the article body
// links to it or the pattern page lists the problem among its examples (premium articles
// hide their body links, so they rely on the pattern pages alone).
//
// 16 of the system design questions already existed in the curated bank and are merged
// there (prisma/seed-data/system-design.ts). The rest are defined below. Requirements are
// paraphrased from each page's public section; estimation notes, reference solutions,
// and pitfalls are original outlines. Companies are left empty because Hello Interview
// does not say which companies ask each question.
// Consumed by prisma/seed-hello-interview.ts and prisma/seed.ts.

import { LLD_CATEGORY } from "../../types/system-design";
import type { SDQuestionSeed } from "./system-design";

export const HELLO_INTERVIEW_SOURCE = "HelloInterview";

export const HELLO_INTERVIEW_PATTERNS = [
  "Real-time Updates",
  "Dealing with Contention",
  "Multi-step Processes",
  "Scaling Reads",
  "Scaling Writes",
  "Handling Large Blobs",
  "Managing Long Running Tasks",
] as const;

type HelloInterviewPattern = (typeof HELLO_INTERVIEW_PATTERNS)[number];

export type HelloInterviewEntry = {
  name: string; // Hello Interview's list name
  kind: "system-design" | "low-level-design";
  hiSlug: string; // path segment on hellointerview.com
  slug: string; // our question slug
  difficulty: "easy" | "medium" | "hard";
  patterns: HelloInterviewPattern[];
};

export const HELLO_INTERVIEW_LIST: HelloInterviewEntry[] = [
  { name: "Bitly", kind: "system-design", hiSlug: "bitly", slug: "design-url-shortener", difficulty: "easy", patterns: ["Scaling Reads"] },
  { name: "Dropbox", kind: "system-design", hiSlug: "dropbox", slug: "design-dropbox", difficulty: "easy", patterns: ["Handling Large Blobs"] },
  { name: "Local Delivery Service", kind: "system-design", hiSlug: "gopuff", slug: "design-local-delivery-service", difficulty: "easy", patterns: ["Scaling Reads"] },
  { name: "Ticketmaster", kind: "system-design", hiSlug: "ticketmaster", slug: "design-ticketmaster", difficulty: "medium", patterns: ["Real-time Updates", "Dealing with Contention", "Scaling Reads"] },
  { name: "FB News Feed", kind: "system-design", hiSlug: "fb-news-feed", slug: "design-fb-news-feed", difficulty: "medium", patterns: ["Scaling Reads"] },
  { name: "Tinder", kind: "system-design", hiSlug: "tinder", slug: "design-tinder", difficulty: "medium", patterns: [] },
  { name: "LeetCode", kind: "system-design", hiSlug: "leetcode", slug: "design-leetcode", difficulty: "medium", patterns: ["Managing Long Running Tasks"] },
  { name: "WhatsApp", kind: "system-design", hiSlug: "whatsapp", slug: "design-whatsapp", difficulty: "medium", patterns: ["Real-time Updates"] },
  { name: "Rate Limiter", kind: "system-design", hiSlug: "distributed-rate-limiter", slug: "design-rate-limiter", difficulty: "medium", patterns: ["Dealing with Contention", "Scaling Reads", "Scaling Writes"] },
  { name: "YouTube", kind: "system-design", hiSlug: "youtube", slug: "design-youtube", difficulty: "medium", patterns: ["Scaling Reads", "Handling Large Blobs"] },
  { name: "FB Live Comments", kind: "system-design", hiSlug: "fb-live-comments", slug: "design-fb-live-comments", difficulty: "medium", patterns: ["Real-time Updates"] },
  { name: "YouTube Top K", kind: "system-design", hiSlug: "top-k", slug: "design-youtube-top-k", difficulty: "hard", patterns: ["Scaling Reads", "Scaling Writes"] },
  { name: "Uber", kind: "system-design", hiSlug: "uber", slug: "design-uber", difficulty: "hard", patterns: ["Real-time Updates", "Multi-step Processes"] },
  { name: "Web Crawler", kind: "system-design", hiSlug: "web-crawler", slug: "design-web-crawler", difficulty: "hard", patterns: [] },
  { name: "Ad Click Aggregator", kind: "system-design", hiSlug: "ad-click-aggregator", slug: "design-ad-click-aggregator", difficulty: "hard", patterns: ["Scaling Writes"] },
  { name: "FB Post Search", kind: "system-design", hiSlug: "fb-post-search", slug: "design-fb-post-search", difficulty: "hard", patterns: ["Scaling Reads", "Scaling Writes"] },
  { name: "Yelp", kind: "system-design", hiSlug: "yelp", slug: "design-yelp", difficulty: "easy", patterns: ["Scaling Reads"] },
  { name: "Instagram", kind: "system-design", hiSlug: "instagram", slug: "design-instagram", difficulty: "medium", patterns: ["Scaling Reads"] },
  { name: "Strava", kind: "system-design", hiSlug: "strava", slug: "design-strava", difficulty: "medium", patterns: ["Real-time Updates", "Scaling Writes"] },
  { name: "Distributed Cache", kind: "system-design", hiSlug: "distributed-cache", slug: "design-distributed-cache", difficulty: "medium", patterns: ["Scaling Reads"] },
  { name: "Online Auction", kind: "system-design", hiSlug: "online-auction", slug: "design-online-auction", difficulty: "medium", patterns: ["Real-time Updates"] },
  { name: "Job Scheduler", kind: "system-design", hiSlug: "job-scheduler", slug: "design-job-scheduler", difficulty: "medium", patterns: ["Scaling Writes"] },
  { name: "News Aggregator", kind: "system-design", hiSlug: "google-news", slug: "design-news-aggregator", difficulty: "medium", patterns: ["Scaling Reads"] },
  { name: "Price Tracking Service", kind: "system-design", hiSlug: "camelcamelcamel", slug: "design-price-tracking-service", difficulty: "medium", patterns: [] },
  { name: "Notification System", kind: "system-design", hiSlug: "notification-system", slug: "design-notification-system", difficulty: "medium", patterns: ["Multi-step Processes", "Scaling Writes"] },
  { name: "Robinhood", kind: "system-design", hiSlug: "robinhood", slug: "design-robinhood", difficulty: "hard", patterns: ["Real-time Updates"] },
  { name: "Google Docs", kind: "system-design", hiSlug: "google-docs", slug: "design-google-docs", difficulty: "hard", patterns: ["Real-time Updates"] },
  { name: "Payment System", kind: "system-design", hiSlug: "payment-system", slug: "design-payment-system", difficulty: "hard", patterns: ["Multi-step Processes"] },
  { name: "Metrics Monitoring", kind: "system-design", hiSlug: "metrics-monitoring", slug: "design-metrics-monitoring", difficulty: "hard", patterns: ["Scaling Reads", "Scaling Writes"] },
  { name: "Online Chess", kind: "system-design", hiSlug: "online-chess", slug: "design-online-chess", difficulty: "hard", patterns: ["Real-time Updates"] },
  { name: "ChatGPT", kind: "system-design", hiSlug: "chatgpt", slug: "design-chatgpt", difficulty: "hard", patterns: ["Real-time Updates"] },
  { name: "Flash Sale", kind: "system-design", hiSlug: "flash-sale", slug: "design-flash-sale", difficulty: "hard", patterns: ["Real-time Updates", "Scaling Writes"] },

  { name: "Connect Four", kind: "low-level-design", hiSlug: "connect-four", slug: "lld-connect-four", difficulty: "easy", patterns: [] },
  { name: "Amazon Locker", kind: "low-level-design", hiSlug: "amazon-locker", slug: "lld-amazon-locker", difficulty: "easy", patterns: [] },
  { name: "Elevator", kind: "low-level-design", hiSlug: "elevator", slug: "lld-elevator", difficulty: "medium", patterns: [] },
  { name: "Parking Lot", kind: "low-level-design", hiSlug: "parking-lot", slug: "lld-parking-lot", difficulty: "medium", patterns: [] },
  { name: "File System", kind: "low-level-design", hiSlug: "file-system", slug: "lld-file-system", difficulty: "medium", patterns: [] },
  { name: "Movie Ticket Booking", kind: "low-level-design", hiSlug: "bookmyshow", slug: "lld-movie-ticket-booking", difficulty: "medium", patterns: [] },
  { name: "Logging Service", kind: "low-level-design", hiSlug: "logging-service", slug: "lld-logging-service", difficulty: "medium", patterns: [] },
  { name: "Rate Limiter", kind: "low-level-design", hiSlug: "rate-limiter", slug: "lld-rate-limiter", difficulty: "hard", patterns: [] },
  { name: "Inventory Management", kind: "low-level-design", hiSlug: "inventory-management", slug: "lld-inventory-management", difficulty: "hard", patterns: [] },
];

// LLD topic links inferred from a premium page's public requirements and entities rather
// than stated in its readable text. The seeder's dry run lists them separately for review.
export const LLD_INFERRED_TOPIC_LINKS: Record<string, string[]> = {
  "lld-parking-lot": ["Strategy Pattern"],
  "lld-file-system": ["Composition over Inheritance"],
  "lld-rate-limiter": ["Strategy Pattern"],
};

export function helloInterviewUrl(entry: Pick<HelloInterviewEntry, "kind" | "hiSlug">): string {
  return `https://www.hellointerview.com/learn/${entry.kind}/problem-breakdowns/${entry.hiSlug}`;
}

const SD = "https://www.hellointerview.com/learn/system-design/problem-breakdowns/";
const LLD = "https://www.hellointerview.com/learn/low-level-design/problem-breakdowns/";

// System design questions from Hello Interview that are not in the curated bank.
export const HELLO_INTERVIEW_SD_QUESTIONS: SDQuestionSeed[] = [
  {
    slug: "design-local-delivery-service",
    title: "Design a Local Delivery Service (Gopuff)",
    difficulty: "easy",
    category: "Geo",
    source: "HelloInterview",
    url: `${SD}gopuff`,
    prompt: "Design a rapid local delivery service that stocks items in many distribution centers (DCs): customers check which items can reach them within an hour and place multi-item orders.",
    functionalRequirements: "- Query availability of items deliverable within 1 hour to a location\n- Order multiple items at once\n- Out of scope: payments, driver routing, catalog search, cancellations/returns",
    nonFunctionalRequirements: "- Availability lookups < 100ms (they back search)\n- Ordering is strongly consistent: two customers can never buy the same physical unit\n- ~10K DCs and ~100K catalog items\n- ~10M orders/day",
    estimationNotes: "- 10M orders/day ≈ 115 orders/s average, several times that at peak\n- Availability reads outnumber orders heavily (every browse and search checks stock)\n- Inventory rows ≈ DCs × stocked items — millions, fits a single well-indexed relational DB",
    referenceSolution: "1. **Entities**: Item (catalog), DistributionCenter (location), Inventory (item × DC quantity), Order + OrderItems.\n2. **Nearby DCs**: find DCs that can deliver within an hour — start with a radius query, refine with travel-time estimates from a routing/ETA provider; cache the DC set per region/geohash.\n3. **Availability**: sum inventory for the requested items across those DCs; serve from read replicas and a short-TTL cache.\n4. **Ordering**: a single transaction that checks and decrements inventory rows (row locks or conditional updates) and inserts the order — keep inventory and orders in the same strongly consistent store.\n5. **Scale**: partition by region if one DB is no longer enough; reads scale with replicas and caching.",
    commonPitfalls: "- Using straight-line distance only, ignoring drive time\n- Checking availability from a cache inside the order path (overselling)\n- Splitting inventory and orders across stores without a transaction",
    topics: ["Geohashing & QuadTree", "Caching", "Replication", "Eventual vs Strong Consistency", "Scaling Reads"],
    companies: [],
  },
  {
    slug: "design-tinder",
    title: "Design Tinder (Dating App)",
    difficulty: "medium",
    category: "Geo",
    source: "HelloInterview",
    url: `${SD}tinder`,
    prompt: "Design a location-based dating app: users set preferences and a maximum distance, swipe through a stack of nearby profiles, and get notified when two users both swipe right.",
    functionalRequirements: "- Create a profile with preferences (age range, interests) and a max distance\n- View a stack of potential matches that fit the preferences and distance\n- Swipe right/left on profiles one at a time\n- Get a match notification when both users swipe right\n- Out of scope: photo upload, chat, premium features, fake-profile detection",
    nonFunctionalRequirements: "- Strong consistency for swipes and matches (a mutual swipe must always produce a match)\n- ~20M DAU, ~100 swipes per user per day\n- Load the match stack in < 300ms\n- Never show profiles the user already swiped on",
    estimationNotes: "- 20M × 100 = 2B swipes/day ≈ 23K swipes/s average\n- Swipe history grows ~2B rows/day — needs a partitioned store\n- Stack generation is read-heavy geo + preference filtering",
    referenceSolution: "1. **Entities**: Profile (preferences, last location), Swipe (swiper, swipee, decision), Match.\n2. **Swipes**: write to a store partitioned by user pair so both directions land together; check for the reverse swipe atomically (e.g. a Redis script or a conditional write keyed on the sorted pair) to create exactly one match.\n3. **Stack generation**: geo + preference query on an indexed store (geohash / search index); precompute and cache a stack per active user, refreshing in the background.\n4. **Already-swiped filtering**: check candidates against the user's swipe history; a per-user Bloom filter keeps this cheap for heavy swipers.\n5. **Notifications**: on match, push to both users via a notification service.",
    commonPitfalls: "- Non-atomic mutual-swipe check (two concurrent right swipes, no match)\n- Running an expensive geo + filter query on every swipe\n- Showing previously swiped profiles again",
    topics: ["Geohashing & QuadTree", "Caching", "Bloom Filters", "Eventual vs Strong Consistency"],
    companies: [],
  },
  {
    slug: "design-leetcode",
    title: "Design LeetCode (Online Judge)",
    difficulty: "medium",
    category: "Infra/Primitive",
    source: "HelloInterview",
    url: `${SD}leetcode`,
    prompt: "Design an online coding platform: users browse problems, write solutions in several languages, submit them to be run against test cases, and follow a live leaderboard during competitions.",
    functionalRequirements: "- View a list of coding problems\n- View a problem and code a solution in multiple languages\n- Submit a solution and get feedback quickly\n- View a live leaderboard during competitions\n- Out of scope: auth, profiles, payments, analytics, social features",
    nonFunctionalRequirements: "- Availability over consistency\n- Isolation and security when running untrusted user code\n- Submission results within ~5 seconds\n- Competitions with ~100K concurrent users",
    estimationNotes: "- 100K users submitting every few minutes near the end of a contest ≈ hundreds to low thousands of submissions/s at peak\n- Each run is CPU-bound for seconds — capacity is the number of sandboxes",
    referenceSolution: "1. **Problems** served from a DB + cache (static, read-heavy).\n2. **Submission flow**: API validates and enqueues the submission; the client polls (or subscribes) for the result.\n3. **Execution**: workers pull from the queue and run code in isolated containers per language — no network, read-only filesystem, CPU/memory/time limits, seccomp.\n4. **Test cases**: run the solution against stored cases inside the sandbox with a per-case timeout; record the verdict.\n5. **Leaderboard**: Redis sorted set per competition, updated when a verdict lands; clients poll every few seconds.\n6. **Scale**: autoscale workers on queue depth; the queue absorbs contest spikes.",
    commonPitfalls: "- Running user code in the API process or without resource limits\n- Synchronous submission handling (timeouts under load)\n- Computing the leaderboard with a DB query on every refresh",
    topics: ["Message Queues", "Caching", "Backpressure", "Managing Long Running Tasks"],
    companies: [],
  },
  {
    slug: "design-fb-live-comments",
    title: "Design Facebook Live Comments",
    difficulty: "medium",
    category: "Messaging",
    source: "HelloInterview",
    url: `${SD}fb-live-comments`,
    prompt: "Design the comment stream for live videos: viewers post comments and see everyone's new comments appear in near real time while watching.",
    functionalRequirements: "- Post a comment on a live video\n- See new comments in near real time while watching\n- See comments posted before joining\n- Out of scope: replies, reactions, moderation, auth",
    nonFunctionalRequirements: "- Millions of concurrent live videos; thousands of comments/s on the hottest videos\n- Availability over consistency; eventual consistency is fine\n- < 200ms end-to-end broadcast latency",
    estimationNotes: "- A viral video can have millions of viewers — fan-out, not writes, is the bottleneck\n- Comment writes are small; storage is modest",
    referenceSolution: "1. **Write path**: POST comment → comment service → durable store partitioned by videoId (e.g. Cassandra/DynamoDB) → publish to the video's channel.\n2. **Delivery**: viewers hold an SSE/WebSocket connection to a realtime server; SSE fits because traffic is mostly server → client.\n3. **Fan-out across servers**: pub/sub keyed by videoId (Redis pub/sub or similar); each realtime server subscribes to the videos its viewers watch.\n4. **Co-locate viewers**: route viewers of the same video to the same servers (consistent hashing on videoId) to cut subscription fan-out.\n5. **History**: on join, page back through recent comments with a cursor; on reconnect, resume from the last seen comment id.",
    commonPitfalls: "- Polling the DB for new comments\n- Every server subscribing to every video\n- No resume-from-cursor on reconnect (missed comments)",
    topics: ["WebSockets vs Polling", "Pub/Sub", "Database Sharding", "Consistent Hashing", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-youtube-top-k",
    title: "Design YouTube Top K Videos",
    difficulty: "hard",
    category: "Streaming",
    source: "HelloInterview",
    url: `${SD}top-k`,
    prompt: "Design a service that returns the top K most-viewed videos for fixed time windows (last hour, day, month) and all time, fed by a massive stream of view events.",
    functionalRequirements: "- Query the top K videos all-time (K up to 1,000)\n- Query top K for tumbling windows of 1 hour, 1 day, 1 month\n- Out of scope: arbitrary windows or start/end points",
    nonFunctionalRequirements: "- At most ~1 minute between a view and it being counted\n- Exact results — no approximation\n- Queries return in tens of milliseconds\n- Massive view rate and a massive number of videos",
    estimationNotes: "- ~billions of views/day ≈ 50K–100K+ view events/s\n- Billions of videos, but top-K results are tiny (≤ 1,000 ids)",
    referenceSolution: "1. **Ingestion**: view events into a partitioned log (Kafka) keyed by videoId.\n2. **Counting**: stream processors own a subset of videos, keep per-window counts in memory, and checkpoint/snapshot for recovery.\n3. **Top-K per partition**: each processor maintains a min-heap of its local top K per window; a merge step combines partition heaps into the global top K.\n4. **Windows**: tumbling windows keyed by bucket start; roll counts over at the boundary and keep all-time totals separately.\n5. **Serving**: write each window's global top K to a cache; queries read precomputed results.\n6. **Replay**: rebuild state from the log's retention on failure.",
    commonPitfalls: "- Incrementing a DB counter per view\n- Sorting all videos at query time\n- Using approximate sketches when exact results are required",
    topics: ["Pub/Sub", "Database Sharding", "Caching", "Write-Ahead Log", "Scaling Reads", "Scaling Writes"],
    companies: [],
  },
  {
    slug: "design-fb-post-search",
    title: "Design Facebook Post Search",
    difficulty: "hard",
    category: "Social/Feed",
    source: "HelloInterview",
    url: `${SD}fb-post-search`,
    prompt: "Design keyword search over all posts on a social network, returning results sorted by recency or like count, without using an off-the-shelf search engine.",
    functionalRequirements: "- Create and like posts\n- Search posts by keyword\n- Sort results by recency or like count\n- Out of scope: fuzzy matching, personalization, privacy filters, complex relevance, media, live-updating results",
    nonFunctionalRequirements: "- Median query < 500ms\n- High request volume\n- New posts searchable within ~1 minute\n- All posts discoverable, including old/unpopular ones\n- Highly available",
    estimationNotes: "- Billions of posts, 100M+ new posts/day\n- Likes arrive far more often than posts — like counts are the hot write path",
    referenceSolution: "1. **Inverted index**: keyword → posting lists of postIds, kept in two orders (by time and by like count), sharded by keyword.\n2. **Ingestion**: post create/like events go to a log; indexers tokenize posts and update posting lists asynchronously (meets the 1-minute freshness bar).\n3. **Likes**: batch like-count updates; only re-rank a post in the like-sorted list when its count crosses thresholds, instead of on every like.\n4. **Queries**: fetch the posting list for each keyword; intersect for multi-keyword queries; bigram indexes for phrases.\n5. **Caching**: cache hot query results at the edge/in Redis with short TTLs.\n6. **Storage tiers**: keep recent/hot postings in memory, older ones on cheaper storage.",
    commonPitfalls: "- LIKE '%term%' scans on the post table\n- Re-indexing a post on every single like\n- Ignoring hot keywords that concentrate load on one shard",
    topics: ["Indexing", "Change Data Capture", "Caching", "Database Sharding", "Scaling Reads", "Scaling Writes"],
    companies: [],
  },
  {
    slug: "design-strava",
    title: "Design Strava (Fitness Tracking)",
    difficulty: "medium",
    category: "Geo",
    source: "HelloInterview",
    url: `${SD}strava`,
    prompt: "Design a fitness tracking app: users record runs and rides with live stats, save them, and view their own and their friends' completed activities.",
    functionalRequirements: "- Start, pause, stop, and save runs and rides\n- See live activity data (route, distance, time) while active\n- View details of your own and friends' completed activities\n- Out of scope: friend management, auth, comments/likes",
    nonFunctionalRequirements: "- Availability over consistency\n- Work offline in remote areas\n- Accurate, up-to-date stats during the activity\n- ~10M concurrent activities",
    estimationNotes: "- 10M concurrent activities × a GPS point every few seconds ≈ millions of points/s if streamed\n- Storing a whole route per activity ≈ tens of KB",
    referenceSolution: "1. **Client-first**: the device records GPS points and computes distance/time locally, buffering on-device so tracking works offline.\n2. **Upload**: sync points in periodic batches (or once on completion) instead of streaming every point — cuts write load by orders of magnitude.\n3. **Storage**: Activity metadata in a DB; the route as a compact blob or point list, partitioned by user/activity.\n4. **Friends' activities**: query activities by friend ids, time-ordered and paginated; cache recent activity feeds.\n5. **Live sharing (optional)**: batch-upload points periodically and let friends poll or subscribe to that activity's updates.\n6. **Leaderboards**: aggregate distance per user in a sorted set per time window.",
    commonPitfalls: "- Streaming every GPS point to the server in real time\n- Server-side stats that break offline\n- Unbounded route blobs in a relational row",
    topics: ["Message Queues", "Caching", "Database Sharding", "Real-time Updates", "Scaling Writes"],
    companies: [],
  },
  {
    slug: "design-online-auction",
    title: "Design an Online Auction (eBay)",
    difficulty: "medium",
    category: "Commerce",
    source: "HelloInterview",
    url: `${SD}online-auction`,
    prompt: "Design an online auction platform: sellers list items with a starting price and end time, buyers place bids that must beat the current highest bid, and everyone sees the current highest bid live.",
    functionalRequirements: "- Post an item for auction with a starting price and end date\n- Bid on an item; accept only bids higher than the current highest bid\n- View an auction with its current highest bid\n- Out of scope: search, category filters, price sorting, auction history",
    nonFunctionalRequirements: "- Strong consistency for bids (never accept a lower bid or lose a winning one)\n- Fault tolerant and durable — accepted bids are never lost\n- Show the current highest bid in real time\n- ~10M concurrent auctions",
    estimationNotes: "- Most auctions are quiet; a few spike near their end time\n- Bid volume is modest overall but highly concentrated per hot auction",
    referenceSolution: "1. **Entities**: Auction (item, start price, end time, current max bid), Bid (append-only).\n2. **Placing a bid**: conditional update on the auction row — `UPDATE ... SET max_bid = :amount WHERE id = :id AND max_bid < :amount` — plus inserting the bid, in one transaction (or optimistic concurrency with a version).\n3. **Durability**: accept bids through a durable queue/log so a crash never drops an acknowledged bid.\n4. **Real-time**: publish accepted bids to a per-auction channel; viewers get updates over SSE/WebSocket via pub/sub.\n5. **Ending**: a scheduled job closes auctions at end time and records the winner.\n6. **Scale**: partition auctions by id; hot auctions are serialized on their own row.",
    commonPitfalls: "- Read-then-write bid checks without a lock or condition (race)\n- Polling the DB for the current price\n- Treating a bid as accepted before it is durably stored",
    topics: ["Eventual vs Strong Consistency", "Idempotency", "Pub/Sub", "WebSockets vs Polling", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-news-aggregator",
    title: "Design a News Aggregator (Google News)",
    difficulty: "medium",
    category: "Social/Feed",
    source: "HelloInterview",
    url: `${SD}google-news`,
    prompt: "Design a news aggregator that collects articles from thousands of publishers worldwide and serves an infinitely scrolling feed that links out to the publisher's site.",
    functionalRequirements: "- View an aggregated feed of articles from thousands of publishers\n- Scroll the feed 'infinitely'\n- Click an article to go to the publisher's site\n- Out of scope: interest customization, saved articles, social sharing",
    nonFunctionalRequirements: "- Availability over consistency\n- Feed requests < 200ms\n- Articles appear within ~30 minutes of publication\n- Absorb traffic spikes during breaking news",
    estimationNotes: "- Hundreds of millions of readers vs only thousands of publishers — reads dwarf writes\n- A few hundred thousand new articles/day",
    referenceSolution: "1. **Ingestion**: crawlers poll publisher RSS/sitemaps on a schedule (plus webhooks where offered); dedupe and store article metadata + a thumbnail.\n2. **Feed**: articles ordered by publish time; cursor pagination on (publishedAt, articleId) keeps infinite scroll stable as new articles arrive.\n3. **Serving**: the feed is largely the same for everyone (per region/category) — precompute pages and cache them in Redis and at the CDN.\n4. **Media**: copy thumbnails to object storage and serve through the CDN.\n5. **Spikes**: caching absorbs breaking-news traffic; the origin only sees cache misses.\n6. **Extensions**: category feeds are separate precomputed lists; personalization re-ranks a candidate set.",
    commonPitfalls: "- Offset pagination on a constantly growing feed (duplicates/skips)\n- Hitting publishers' sites on the read path\n- No cache in front of a feed that is identical for most users",
    topics: ["Caching", "CDN", "Message Queues", "Indexing", "Scaling Reads"],
    companies: [],
  },
  {
    slug: "design-price-tracking-service",
    title: "Design a Price Tracking Service (CamelCamelCamel)",
    difficulty: "medium",
    category: "Commerce",
    source: "HelloInterview",
    url: `${SD}camelcamelcamel`,
    prompt: "Design a service that tracks Amazon product prices over time, shows price history charts, and notifies subscribers when a price drops below their threshold.",
    functionalRequirements: "- View price history for products (website or browser extension)\n- Subscribe to price-drop notifications with a threshold\n- Out of scope: product search/discovery, cross-retailer comparison, reviews",
    nonFunctionalRequirements: "- Availability over consistency\n- ~500M products tracked\n- Price history queries < 500ms\n- Notifications within ~1 hour of a price change",
    estimationNotes: "- 500M products; refreshing each daily ≈ 6K fetches/s — popular products need more often\n- Price points: 500M × a few changes/week ≈ billions of rows/year (time-series shaped)",
    referenceSolution: "1. **Collection**: a crawler fleet with a priority scheduler (popular/subscribed products refreshed more often), rate-limited against the retailer.\n2. **Crowdsourced prices**: the browser extension reports prices users see; treat them as untrusted — verify with a crawl before accepting outliers, and rate-limit/score reporters.\n3. **Storage**: price points in a time-series-friendly store partitioned by productId; precompute daily/weekly rollups for charts.\n4. **Change detection**: when a new price is recorded, emit a price-change event to a queue.\n5. **Notifications**: consumers look up subscriptions whose threshold is now met (index subscriptions by productId + threshold) and send via a notification service, deduplicated per subscription.",
    commonPitfalls: "- Crawling all products at the same frequency\n- Trusting extension-reported prices blindly\n- Scanning all subscriptions on every price change",
    topics: ["Message Queues", "Rate Limiting", "Database Sharding", "Idempotency"],
    companies: [],
  },
  {
    slug: "design-robinhood",
    title: "Design Robinhood (Stock Trading)",
    difficulty: "hard",
    category: "Commerce",
    source: "HelloInterview",
    url: `${SD}robinhood`,
    prompt: "Design a retail stock brokerage app: users see live stock prices and create and cancel market and limit orders, which the platform routes to an external exchange.",
    functionalRequirements: "- See live stock prices\n- Create and cancel market and limit orders\n- Out of scope: after-hours trading, ETFs/options/crypto, live order book",
    nonFunctionalRequirements: "- Order state is strongly consistent and never lost\n- Low-latency price updates to many concurrent users\n- High availability during market hours",
    estimationNotes: "- Millions of users watching a few thousand symbols — fan-out, not symbol count, drives load\n- Orders are far fewer than price reads",
    referenceSolution: "1. **Prices**: a service consumes the exchange's market-data feed once and publishes per-symbol updates to pub/sub; clients subscribe to the symbols on screen via SSE/WebSocket servers.\n2. **Orders**: persist the order first (status pending) with a client idempotency key, then submit it to the exchange; record the exchange order id.\n3. **Order updates**: consume the exchange's execution reports/webhooks to move orders through filled/partially filled/cancelled.\n4. **Consistency**: a state machine on the order row with conditional transitions; reconcile periodically against the exchange to catch missed updates.\n5. **Cancels**: forward to the exchange and only mark cancelled on confirmation.",
    commonPitfalls: "- Every client polling or connecting to the exchange directly\n- Submitting to the exchange before persisting the order\n- Assuming a cancel succeeded before the exchange confirms",
    topics: ["WebSockets vs Polling", "Pub/Sub", "Idempotency", "Eventual vs Strong Consistency", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-google-docs",
    title: "Design Google Docs (Collaborative Editor)",
    difficulty: "hard",
    category: "Storage",
    source: "HelloInterview",
    url: `${SD}google-docs`,
    prompt: "Design a collaborative document editor where many users edit the same document at once and see each other's changes, cursors, and presence in real time.",
    functionalRequirements: "- Create documents\n- Multiple users edit the same document concurrently\n- See others' changes in real time\n- See other users' cursor positions and presence\n- Out of scope: rich structure (plain text is enough), permissions, version history",
    nonFunctionalRequirements: "- Edits converge to the same document for everyone\n- Low-latency propagation of edits\n- Millions of concurrent connections; durable documents",
    estimationNotes: "- Most documents have few concurrent editors; a few have many\n- Operation logs grow without bound unless compacted",
    referenceSolution: "1. **Conflict resolution**: Operational Transformation (a central server orders and transforms ops) or CRDTs; OT with a single authority per document is the classic interview answer.\n2. **Document servers**: every editor of a document connects (WebSocket) to the same server, chosen by consistent hashing on docId; that server orders ops, transforms them, and broadcasts.\n3. **Persistence**: append each op to a durable op log per document; periodically snapshot and compact so loading doesn't replay history from the start.\n4. **Presence and cursors**: ephemeral state held in memory on the document server, never persisted.\n5. **Scale**: add document servers; rebalance by moving documents with connection handoff.",
    commonPitfalls: "- Last-writer-wins on whole documents (lost edits)\n- Editors of one document spread across servers with no single ordering authority\n- Unbounded op logs with no snapshots",
    topics: ["WebSockets vs Polling", "Consistent Hashing", "Write-Ahead Log", "Eventual vs Strong Consistency", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-metrics-monitoring",
    title: "Design a Metrics Monitoring Platform (Datadog)",
    difficulty: "hard",
    category: "Infra/Primitive",
    source: "HelloInterview",
    url: `${SD}metrics-monitoring`,
    prompt: "Design a metrics monitoring platform: services emit metrics, users query dashboards over time ranges, and alert rules notify on-call engineers when thresholds are breached.",
    functionalRequirements: "- Ingest metrics (CPU, memory, latency, custom counters) from services\n- Query and chart metrics with filters, aggregations, and time ranges\n- Define alert rules with thresholds over windows (e.g. p99 > 500ms for 5 minutes)\n- Notify via email, Slack, PagerDuty when alerts fire\n- Out of scope: logs, tracing, ML anomaly detection",
    nonFunctionalRequirements: "- Ingest ~5M metric points/s from ~500K servers\n- Dashboards over days/weeks return within seconds\n- Alerts fire < 1 minute after the metric is emitted\n- Highly available; tolerate late and out-of-order data",
    estimationNotes: "- 5M points/s × ~16 bytes compressed ≈ 80MB/s ≈ 7TB/day raw\n- Long-range queries need rollups (1m, 1h) rather than raw points",
    referenceSolution: "1. **Ingestion**: agents batch points to a collector tier that writes to a partitioned log (Kafka) — the buffer during spikes.\n2. **Storage**: a time-series database partitioned by series (metric + tags) and time; compress with delta/Gorilla encoding.\n3. **Rollups**: stream jobs downsample into 1-minute and 1-hour tiers; dashboards pick the coarsest tier that fits the range.\n4. **Alerting**: evaluate rules in the stream (windowed aggregates per series) instead of polling the TSDB, then hand firing alerts to a notification service with dedup and silencing.\n5. **Cardinality**: cap and monitor tag cardinality per customer; reject or aggregate unbounded tags (user ids, request ids).\n6. **Late data**: watermarks with allowed lateness; correct rollups when late points arrive.",
    commonPitfalls: "- Querying raw points for month-long dashboards\n- Alert rules that poll the database every few seconds\n- Unbounded tag cardinality blowing up the index",
    topics: ["Message Queues", "Database Sharding", "Backpressure", "Pub/Sub", "Scaling Reads", "Scaling Writes"],
    companies: [],
  },
  {
    slug: "design-online-chess",
    title: "Design an Online Chess Platform",
    difficulty: "hard",
    category: "Messaging",
    source: "HelloInterview",
    url: `${SD}online-chess`,
    prompt: "Design an online chess platform with skill-based matchmaking, real-time games with fair clocks, and a global rating leaderboard.",
    functionalRequirements: "- Find an opponent through skill-based matchmaking and start a game\n- Play in real time\n- View a global leaderboard and your own rank, updated shortly after games end\n- Out of scope: spectating, chat/social, puzzles, tournaments, anti-cheat",
    nonFunctionalRequirements: "- ~500K concurrent games at peak (~1M connections)\n- Correct, fast leaderboard over ~10M players\n- Fair clocks despite uneven player latency",
    estimationNotes: "- 1M connections ≈ a few dozen well-tuned WebSocket servers\n- Moves are tiny and infrequent per game — connections, not bandwidth, are the constraint",
    referenceSolution: "1. **Matchmaking**: a queue bucketed by rating range and time control; widen the acceptable range the longer a player waits; pair atomically (e.g. a Redis script) so a player is never matched twice.\n2. **Game servers**: both players connect via WebSocket to the server that owns the game (consistent hashing on gameId); the server validates moves and holds authoritative state.\n3. **Clocks**: the server is the clock authority; timestamp moves on arrival and compensate for measured round-trip latency within a cap.\n4. **Durability**: append moves to a store so games survive server failure and can be restored on another node.\n5. **Leaderboard**: update ratings after each game; a Redis sorted set answers top-N and rank-of-player in O(log n).",
    commonPitfalls: "- Trusting client clocks or client-side move validation\n- Non-atomic pairing that double-books players\n- Computing ranks with ORDER BY over 10M rows",
    topics: ["WebSockets vs Polling", "Consistent Hashing", "Caching", "Idempotency", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-chatgpt",
    title: "Design ChatGPT",
    difficulty: "hard",
    category: "Streaming",
    source: "HelloInterview",
    url: `${SD}chatgpt`,
    prompt: "Design a chat assistant backed by large language models: users send prompts, receive streamed AI responses, and can resume past conversations with their earlier context.",
    functionalRequirements: "- Send a prompt and receive a streamed AI-generated response\n- View past chats and resume them, carrying prior context into the prompt\n- Out of scope: editing/branching messages, multimodal I/O, sharing, tools/browsing, chat search",
    nonFunctionalRequirements: "- Low time to first token\n- ~200M DAU, ~20K prompts/s at peak, ~120K concurrent streaming responses\n- GPU capacity is scarce and expensive",
    estimationNotes: "- 120K concurrent streams × tens of tokens/s ≈ millions of tokens/s generated\n- GPUs, not web servers, are the bottleneck and the cost driver",
    referenceSolution: "1. **Streaming**: stream tokens to the client over SSE as the model produces them.\n2. **Chat storage**: conversations and messages in a store partitioned by user/conversation; assemble context from recent messages (plus a summary of older ones) within the model's context window.\n3. **Inference routing**: a scheduler queues requests per model and dispatches to GPU workers by load and KV-cache locality (keep a conversation on the worker that holds its prefix cache).\n4. **Resilience**: write generated tokens to a buffer/stream (e.g. Redis stream) so a client that reconnects — or lands on a new server after a deploy — resumes from the last token.\n5. **Fairness and cost**: per-user rate limits and tier-based priority queues; summarize or truncate long histories to cap tokens per request.",
    commonPitfalls: "- Buffering the whole response before sending (slow time to first token)\n- Losing an in-flight response when the connection or server drops\n- Sending entire unbounded chat histories to the model",
    topics: ["WebSockets vs Polling", "Rate Limiting", "Load Balancing", "Backpressure", "Real-time Updates"],
    companies: [],
  },
  {
    slug: "design-flash-sale",
    title: "Design a Flash Sale System",
    difficulty: "hard",
    category: "Commerce",
    source: "HelloInterview",
    url: `${SD}flash-sale`,
    prompt: "Design a flash sale where millions of users arrive at once for a small, fixed inventory: users reserve a unit for a limited time and complete payment to buy it.",
    functionalRequirements: "- View the flash sale item\n- Reserve an available unit for a limited time while the sale is active\n- Complete payment for a reserved unit\n- Out of scope: catalog browsing/search, shipping/returns/order history, sale administration",
    nonFunctionalRequirements: "- Never sell more units than exist, under extreme contention\n- Release expired reservations promptly\n- Survive millions of users arriving at the same moment\n- Fair access to limited inventory",
    estimationNotes: "- Millions of requests in the first seconds for maybe thousands of units — nearly all requests fail, so rejecting them cheaply matters most\n- The item page is identical for everyone",
    referenceSolution: "1. **Static content**: serve the item page from the CDN; only reserve/pay calls reach the backend.\n2. **Admission**: a virtual waiting room / queue in front of the reserve endpoint lets users through at a controlled rate (and gives FIFO fairness).\n3. **Inventory**: an atomic counter (Redis DECR or a Lua script) as the fast gate, backed by conditional DB writes for the reservation record — never read-then-write.\n4. **Reservations**: store expiresAt; release expired holds with a delayed queue or sweeper and return units to the counter.\n5. **Payment**: idempotent, keyed by reservation id; confirm the sale only after payment succeeds.\n6. **Live stock**: broadcast remaining inventory/sold-out state to waiting clients over SSE.",
    commonPitfalls: "- Letting the full spike hit the database\n- Non-atomic stock checks (overselling)\n- Reservations that never expire, stranding inventory",
    topics: ["Eventual vs Strong Consistency", "Idempotency", "Rate Limiting", "Message Queues", "Real-time Updates", "Scaling Writes"],
    companies: [],
  },
];

// Low-level (object-oriented) design questions. They share the system design tables with
// category "Low-Level Design" and are excluded from system design readiness analytics.
// Topics come from what each page shows; premium pages expose only the problem,
// requirements, entities, and section headings.
export const HELLO_INTERVIEW_LLD_QUESTIONS: SDQuestionSeed[] = [
  {
    slug: "lld-connect-four",
    title: "Design Connect Four (LLD)",
    difficulty: "easy",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}connect-four`,
    prompt: "Design the classes for a two-player Connect Four game on a 7-column, 6-row board: players take turns dropping discs, and the first to connect four in a row, column, or diagonal wins.",
    functionalRequirements: "- Two players alternate dropping discs into a 7×6 board\n- A disc falls to the lowest empty row in its column\n- The game ends on four in a row (vertical, horizontal, diagonal) or a full board (draw)\n- Reject invalid moves: full column, out of turn, after the game is over\n- Out of scope: UI, concurrent games, move history/undo, configurable board size",
    nonFunctionalRequirements: "- Clear, cohesive classes that are easy to extend (board size, undo, AI opponent)\n- Invalid moves fail with clear errors",
    referenceSolution: "1. **Entities**: `Game` (players, current turn, state), `Board` (grid, drop disc, check win), `Player`, `DiscColor` enum, `GameState` enum (IN_PROGRESS / WON / DRAW).\n2. **Game.makeMove(player, column)**: validate state and turn → `board.dropDisc(column, color)` → check win/draw → advance turn.\n3. **Board.dropDisc**: scan from the bottom of the column for the first empty cell; throw if full; return the landing row.\n4. **Win check**: from the last placed disc only, count matching discs along four direction vectors (horizontal, vertical, two diagonals) in both directions — one method, not a class per direction.\n5. **State**: an explicit `GameState` enum instead of scattered boolean flags.",
    commonPitfalls: "- Scanning the whole board for a winner after every move\n- Separate win-checker classes per direction (over-engineering)\n- Boolean flags (isOver, isDraw) that can contradict each other",
    topics: ["State Machines"],
    companies: [],
  },
  {
    slug: "lld-amazon-locker",
    title: "Design Amazon Locker (LLD)",
    difficulty: "easy",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}amazon-locker`,
    prompt: "Design the classes for a self-service package locker: a carrier deposits a package into a compartment of the right size, the system issues an access token, and the customer uses it to retrieve the package.",
    functionalRequirements: "- Carrier deposits a package by size (small/medium/large); the system assigns a free compartment of that size and returns an access token, or an error if none is free\n- One access token per package\n- Customer retrieves the package with the token; invalid, used, or expired tokens are rejected with specific errors\n- Tokens expire after 7 days; expired packages stay until staff remove them\n- Staff can open all compartments holding expired packages\n- Out of scope: delivery logistics, token delivery (SMS/email), lockouts, UI, multiple lockers, payments",
    nonFunctionalRequirements: "- Clear error messages for each failure case\n- Easy to extend (size fallback, compartments under maintenance)",
    referenceSolution: "1. **Entities**: `Locker` (compartments, token index), `Compartment` (id, size, occupied), `AccessToken` (code, compartment, expiresAt, used), `Size` enum.\n2. **deposit(size)**: find a free compartment of that size → mark occupied → create and store a token → return it.\n3. **pickup(code)**: look up the token → reject unknown / used / expired with distinct errors → open the compartment, free it, mark the token used.\n4. **Expiry**: `openExpiredCompartments()` finds tokens past expiresAt and releases those compartments for staff.\n5. **Responsibility**: the token knows whether it is expired; the compartment knows whether it is free (Information Expert) — the Locker coordinates.",
    commonPitfalls: "- One god class holding every rule\n- A single generic 'invalid token' error for all failure modes\n- Freeing the compartment before validating the token",
    topics: ["Responsibility Assignment"],
    companies: [],
  },
  {
    slug: "lld-elevator",
    title: "Design an Elevator System (LLD)",
    difficulty: "medium",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}elevator`,
    prompt: "Design the classes for an elevator controller managing 3 elevators across 10 floors: hall calls pick an elevator to dispatch, passengers choose destinations, and a step() call advances the simulation.",
    functionalRequirements: "- 3 elevators serving floors 0–9\n- Hall calls from any floor with a direction (UP/DOWN); the system chooses which elevator to dispatch\n- Passengers select one or more destination floors inside the car\n- Simulation advances in discrete steps via step()/tick()\n- Handle multiple pending requests; reject non-existent floors; a request for the current floor is a no-op\n- Out of scope: capacity/weight, doors, emergency stop, dynamic configuration, UI",
    nonFunctionalRequirements: "- Efficient movement (no ping-ponging between floors)\n- Dispatch policy can change without rewriting the controller",
    referenceSolution: "1. **Entities**: `ElevatorController` (elevators, dispatch strategy), `Elevator` (current floor, direction, pending stops), `Request` (floor, type: HALL/DESTINATION, direction).\n2. **Direction state**: IDLE / UP / DOWN per elevator.\n3. **Movement (SCAN)**: keep moving in the current direction while stops remain ahead; reverse when none do; go IDLE when empty.\n4. **Dispatch**: a `DispatchStrategy` interface with `selectBestElevator(request)` — e.g. nearest idle, or an elevator already moving toward the floor in the requested direction; swap implementations without touching the controller.\n5. **step()**: each elevator moves one floor or services its current floor.\n6. **Concurrency extension**: guard addRequest with a lock or feed requests through a thread-safe queue.",
    commonPitfalls: "- First-come-first-served stops (constant direction reversals)\n- Dispatch logic hard-coded inside the controller\n- Ignoring hall-call direction when choosing an elevator",
    topics: ["Strategy Pattern", "Scheduling Algorithms", "State Machines"],
    companies: [],
  },
  {
    slug: "lld-parking-lot",
    title: "Design a Parking Lot (LLD)",
    difficulty: "medium",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}parking-lot`,
    prompt: "Design the classes for a parking lot that assigns compatible spots to motorcycles, cars, and large vehicles, issues tickets on entry, and charges an hourly fee on exit.",
    functionalRequirements: "- Three vehicle types: motorcycle, car, large vehicle\n- On entry, assign an available compatible spot and issue a ticket\n- On exit, validate the ticket, charge hourly (rounded up), and free the spot\n- Same hourly rate for all vehicles\n- Reject entry when no compatible spot is free; reject invalid or already-used tickets\n- Out of scope: payment processing, gates, cameras, displays, reservations",
    nonFunctionalRequirements: "- Extensible to multiple floors, per-type pricing, and multiple entrances",
    referenceSolution: "1. **Entities**: `ParkingLot` (spots, active tickets), `ParkingSpot` (id, size, occupied), `Ticket` (id, spot, vehicle type, entry time, closed), `VehicleType` enum.\n2. **enter(vehicleType)**: find a free compatible spot (index free spots by size) → occupy it → create a ticket.\n3. **exit(ticketId)**: validate → compute fee = ceil(hours) × rate → free the spot → close the ticket.\n4. **Pricing**: keep fee calculation behind a small pricing interface so per-type or time-of-day pricing is a new implementation, not an edit.\n5. **Extensions**: floors as a collection of spot groups; multiple entrances need atomic spot allocation (lock or concurrent free-spot queues).",
    commonPitfalls: "- Linear scans over all spots on every entry\n- Pricing logic embedded in the exit method\n- Allowing a ticket to be used twice",
    topics: ["Strategy Pattern", "Concurrency & Locking"],
    companies: [],
  },
  {
    slug: "lld-file-system",
    title: "Design an In-Memory File System (LLD)",
    difficulty: "medium",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}file-system`,
    prompt: "Design the classes for an in-memory hierarchical file system with a single root: create, delete, list, move, and rename files and folders, and resolve absolute paths.",
    functionalRequirements: "- Hierarchy with a single root; folders contain files and folders; files hold string content\n- Create and delete files and folders\n- List a folder's contents\n- Resolve absolute paths (e.g. /home/user/docs)\n- Rename and move files and folders\n- Get the full path of any entry\n- Tens of thousands of entries in memory\n- Out of scope: search, relative paths, permissions/timestamps, persistence, symlinks, UI",
    nonFunctionalRequirements: "- Path resolution cost proportional to path depth\n- Clean shared abstraction for files and folders",
    referenceSolution: "1. **Entities**: abstract `FileSystemEntry` (name, parent), `File` (content), `Folder` (children map name → entry), `FileSystem` (root, operations).\n2. **Path resolution**: split on '/', walk from the root through each folder's children map.\n3. **Full path**: walk parent pointers to the root and join names.\n4. **Move/rename**: detach from the old parent's map, update name/parent, attach to the new parent; reject name collisions and moving a folder into its own subtree.\n5. **Delete**: remove from the parent's map (recursive for folders).\n6. **Thread safety extension**: a read-write lock on the tree, or per-folder locks acquired in a consistent order.",
    commonPitfalls: "- Storing full path strings on every node (moves then require rewriting every descendant)\n- Allowing a folder to be moved into its own descendant\n- Lists instead of maps for children (linear lookups)",
    topics: ["Composition over Inheritance", "Concurrency & Locking"],
    companies: [],
  },
  {
    slug: "lld-movie-ticket-booking",
    title: "Design a Movie Ticket Booking System (LLD)",
    difficulty: "medium",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}bookmyshow`,
    prompt: "Design the classes for a movie ticket booking system: users find movies and showtimes across theaters, pick specific seats, and book or cancel reservations without two people ever getting the same seat.",
    functionalRequirements: "- Search movies by title; browse movies playing at a theater\n- Theaters have multiple screens sharing one seat layout (rows A–Z, seats 0–20)\n- View available seats for a showtime and pick specific ones\n- Book several seats in one reservation and get a confirmation id\n- Concurrent attempts on the same seat: exactly one succeeds\n- Cancel a reservation by confirmation id, releasing its seats\n- Out of scope: payments, varied seat layouts/types, rescheduling, UI",
    nonFunctionalRequirements: "- Thread-safe booking: no double-booking\n- Multi-seat bookings are all-or-nothing",
    referenceSolution: "1. **Entities**: `BookingSystem`, `Theater`, `Movie`, `Showtime` (movie, theater, screen, time, seat state), `Reservation` (id, showtime, seats).\n2. **Seat state per showtime**: a map seatId → reservationId (null when free).\n3. **book(showtime, seats)**: lock the showtime → verify every requested seat is free → assign them all → create the reservation; release the lock. All-or-nothing by checking before assigning.\n4. **cancel(confirmationId)**: lock the showtime → free its seats → remove the reservation.\n5. **Lock granularity**: per showtime, so different shows never contend.\n6. **Extension**: temporary seat holds with an expiry during checkout.",
    commonPitfalls: "- One global lock for the whole system\n- Assigning seats one by one and leaving partial bookings on failure\n- Check-then-set without holding a lock",
    topics: ["Concurrency & Locking"],
    companies: [],
  },
  {
    slug: "lld-logging-service",
    title: "Design a Logging Library (LLD)",
    difficulty: "medium",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}logging-service`,
    prompt: "Design an in-process logging library (like Log4j or Python's logging): application code logs messages at a severity level, and each record is formatted and written to one or more destinations.",
    functionalRequirements: "- Five levels: DEBUG < INFO < WARN < ERROR < FATAL\n- Each record has timestamp, level, message, and thread name\n- Write each record to one or more destinations configured at startup\n- Each destination has its own minimum level and its own format; format and destination type vary independently\n- Concurrent calls are safe: one record's bytes never interleave with another's on the same destination\n- Out of scope: hot-reloading config, async writes, remote destinations (design should allow them), hierarchical loggers",
    nonFunctionalRequirements: "- Adding a new format or destination type needs no changes to existing classes\n- Low overhead on the calling thread",
    referenceSolution: "1. **Entities**: `Logger` (list of sinks), `LogRecord` (timestamp, level, message, thread), `Level` enum, `Formatter` interface (plain text, JSON), `Destination` interface (console, file), `Sink` = destination + formatter + minimum level.\n2. **log(level, msg)**: build a LogRecord once → each sink checks its threshold → formats → writes.\n3. **Composition**: a sink composes a formatter and a destination, so N formats × M destinations needs N + M classes, not N × M subclasses.\n4. **Atomic writes**: each destination serializes writes (a lock around the formatted write) so records never interleave.\n5. **Extensions**: non-blocking logging via a queue drained by a writer thread; named loggers in a hierarchy.",
    commonPitfalls: "- Subclasses per format × destination combination\n- Formatting inside the lock (longer critical sections)\n- A single global level instead of per-destination thresholds",
    topics: ["Composition over Inheritance", "Concurrency & Locking"],
    companies: [],
  },
  {
    slug: "lld-rate-limiter",
    title: "Design a Rate Limiter Library (LLD)",
    difficulty: "hard",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}rate-limiter`,
    prompt: "Design an in-process rate limiter: each API endpoint is configured with an algorithm (token bucket, sliding window log, ...) and its parameters, and every request from a client is allowed or rejected with retry information.",
    functionalRequirements: "- Configuration is loaded once at startup\n- Requests arrive as (clientId, endpoint)\n- Each endpoint names an algorithm and its parameters (e.g. capacity and refill rate for a token bucket)\n- Enforce limits per client per endpoint\n- Return (allowed, remaining, retryAfterMs | null)\n- Unconfigured endpoints use a default limit\n- Out of scope: distributed limiting, dynamic config, metrics, deep config validation",
    nonFunctionalRequirements: "- New algorithms can be added without modifying existing ones\n- Safe under concurrent requests\n- Bounded memory as the number of clients grows",
    referenceSolution: "1. **Entities**: `RateLimiter` (entry point), `Limiter` interface (`tryAcquire(clientId) → RateLimitResult`), `TokenBucketLimiter`, `SlidingWindowLogLimiter`, `LimiterFactory` (config → limiter), `RateLimitResult`.\n2. **Routing**: at startup build one limiter per endpoint from config via the factory; a default limiter for the rest.\n3. **Per-client state**: each limiter keeps a map clientId → state (tokens + last refill time, or a timestamp deque).\n4. **Token bucket**: refill lazily on each call from elapsed time; allow if tokens ≥ 1; retryAfter = time until one token refills.\n5. **Thread safety**: a concurrent map plus per-client locking (or atomic compare-and-set on the state).\n6. **Memory**: evict idle client state after inactivity.",
    commonPitfalls: "- A switch on the algorithm name inside one class\n- Background refill threads per client instead of lazy refill\n- Unbounded per-client maps",
    topics: ["Strategy Pattern", "Concurrency & Locking", "Rate Limiting"],
    companies: [],
  },
  {
    slug: "lld-inventory-management",
    title: "Design an Inventory Management System (LLD)",
    difficulty: "hard",
    category: LLD_CATEGORY,
    source: "HelloInterview",
    url: `${LLD}inventory-management`,
    prompt: "Design the classes for an inventory system tracking product stock across warehouses: receive and ship stock, check which warehouses can fulfil an order, transfer stock, and alert on low stock.",
    functionalRequirements: "- Track stock per product per warehouse\n- Add stock (receiving) and remove stock (fulfilment) at a warehouse\n- Given a product and quantity, return the warehouses that can fulfil it\n- Transfer stock between warehouses\n- Low-stock alerts\n- Reject operations that would make stock negative\n- Thread-safe under concurrent operations\n- Out of scope: product catalog, order processing/payment, persistence",
    nonFunctionalRequirements: "- Transfers are atomic: stock is never lost or duplicated\n- No deadlocks between concurrent transfers",
    referenceSolution: "1. **Entities**: `InventoryManager` (warehouses, alert config, listeners), `Warehouse` (productId → quantity), `AlertConfig` (thresholds), `AlertListener` interface.\n2. **Add/remove**: lock the warehouse → validate (no negative stock) → update → check thresholds and notify listeners after releasing the lock.\n3. **Transfer**: lock both warehouses in a consistent order (e.g. by id) to avoid deadlock → validate source stock → move → unlock.\n4. **Availability**: scan warehouses for sufficient quantity (read under lock or from a consistent snapshot).\n5. **Extensions**: reservations for in-progress orders (reserved vs available quantity); in-transit stock as its own state.",
    commonPitfalls: "- Locking two warehouses in arbitrary order (deadlock)\n- Check-then-act without holding the lock (negative stock)\n- Calling alert listeners while holding the lock",
    topics: ["Concurrency & Locking"],
    companies: [],
  },
];
