// FAANG System Design seed content: curated building-block topics + a canonical
// question bank with framework checklists and reference-solution outlines.
// Consumed by prisma/seed.ts (seedSystemDesign). All rows are seeded globally
// (userId: null), mirroring the coding problem/pattern seed convention.

export type SDTopicSeed = {
  name: string;
  category: string; // Scalability | Storage | Consistency | Networking | Messaging
  description: string;
};

export type SDQuestionSeed = {
  slug: string;
  title: string;
  difficulty: "medium" | "hard";
  category: string; // Infra/Primitive | Social/Feed | Messaging | Streaming | Storage | Geo | Commerce
  prompt: string;
  functionalRequirements: string;
  nonFunctionalRequirements: string;
  estimationNotes: string;
  referenceSolution: string;
  commonPitfalls: string;
  topics: string[]; // must match SD_TOPIC_SEED names
  companies: string[]; // must match CompanyCard names (COMPANY_SEED)
};

export const SD_TOPIC_SEED: SDTopicSeed[] = [
  { name: "Load Balancing", category: "Scalability", description: "L4/L7 balancing, health checks, sticky sessions, and routing strategies." },
  { name: "Caching", category: "Storage", description: "Cache-aside, write-through/back, TTLs, eviction (LRU/LFU), and stampede protection." },
  { name: "CDN", category: "Networking", description: "Edge caching of static/media content, cache invalidation, and origin shielding." },
  { name: "Database Sharding", category: "Storage", description: "Horizontal partitioning by key/range/hash; rebalancing and hot-shard avoidance." },
  { name: "Replication", category: "Storage", description: "Leader-follower vs multi-leader, sync vs async, read replicas, and failover." },
  { name: "Consistent Hashing", category: "Scalability", description: "Minimizing key movement on node add/remove using a hash ring with virtual nodes." },
  { name: "CAP Theorem", category: "Consistency", description: "Consistency/availability/partition-tolerance trade-offs and when to pick each." },
  { name: "SQL vs NoSQL", category: "Storage", description: "Relational vs document/wide-column/KV; modeling for access patterns." },
  { name: "Indexing", category: "Storage", description: "B-tree/LSM indexes, secondary indexes, and inverted indexes for search." },
  { name: "Message Queues", category: "Messaging", description: "Async decoupling, at-least-once delivery, retries, and dead-letter queues." },
  { name: "Pub/Sub", category: "Messaging", description: "Fan-out to many consumers, topics/partitions, and consumer groups." },
  { name: "Rate Limiting", category: "Scalability", description: "Token bucket, leaky bucket, sliding window; distributed counters." },
  { name: "Bloom Filters", category: "Storage", description: "Probabilistic membership checks to avoid expensive lookups (no false negatives)." },
  { name: "Quorum & Consensus", category: "Consistency", description: "R+W>N quorums, Raft/Paxos for agreement and leader election." },
  { name: "Idempotency", category: "Consistency", description: "Safe retries via idempotency keys and dedupe to handle at-least-once delivery." },
  { name: "Backpressure", category: "Messaging", description: "Protecting downstreams under load via buffering, shedding, and flow control." },
  { name: "WebSockets vs Polling", category: "Networking", description: "Long-polling, SSE, and WebSockets for real-time push; connection scaling." },
  { name: "Geohashing & QuadTree", category: "Storage", description: "Spatial indexing for proximity search and nearby queries." },
  { name: "Write-Ahead Log", category: "Storage", description: "Durability and recovery via append-only logs; the basis of LSM and replication." },
  { name: "Change Data Capture", category: "Messaging", description: "Streaming row-level DB changes to derived stores/search/caches." },
  { name: "Leader Election", category: "Consistency", description: "Selecting a coordinator (ZooKeeper/etcd/Raft) and handling split-brain." },
  { name: "API Gateway", category: "Networking", description: "Auth, routing, rate limiting, and aggregation at the edge of a service mesh." },
  { name: "Object Storage", category: "Storage", description: "Blob stores for large immutable media; chunking and presigned URLs." },
  { name: "Eventual vs Strong Consistency", category: "Consistency", description: "Read-your-writes, monotonic reads, and convergence trade-offs." },
];

export const SD_QUESTION_SEED: SDQuestionSeed[] = [
  {
    slug: "design-url-shortener",
    title: "Design a URL Shortener (TinyURL / Bitly)",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a service that converts long URLs into short links and redirects users from the short link to the original URL.",
    functionalRequirements: "- Create a short link for a long URL (optionally custom alias)\n- Redirect short link to original URL\n- Optional: link expiry and basic click analytics",
    nonFunctionalRequirements: "- Read-heavy (~100:1 read:write)\n- Very low redirect latency (<10ms p99)\n- High availability; short links never break",
    estimationNotes: "- 100M new URLs/month ≈ 40 writes/s, ~4K reads/s\n- 7-char base62 key space = 62^7 ≈ 3.5T combinations\n- 5 years storage ≈ 6B rows × ~500B ≈ 3TB",
    referenceSolution: "1. **Key generation**: base62 of an auto-increment counter or a hash of the URL (handle collisions); pre-generate keys with a Key Generation Service to avoid contention.\n2. **Storage**: KV store (key → long URL) — sharded by key; SQL is fine at this scale too.\n3. **Read path**: CDN/edge + cache (Redis) in front; redirect via 301/302.\n4. **Write path**: dedupe identical URLs, store mapping, return short link.\n5. **Analytics**: emit click events to a queue → aggregate offline.",
    commonPitfalls: "- Using a hash without a collision strategy\n- 301 (permanent) caching breaking analytics — prefer 302\n- Not pre-generating keys (counter becomes a bottleneck)",
    topics: ["Caching", "CDN", "Database Sharding", "Consistent Hashing", "SQL vs NoSQL"],
    companies: ["Amazon", "Google", "Facebook", "Microsoft"],
  },
  {
    slug: "design-pastebin",
    title: "Design Pastebin",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a service where users paste text and get a shareable link to view it, with optional expiry.",
    functionalRequirements: "- Create a paste, get a unique URL\n- View a paste by URL\n- Expiry and optional visibility (public/unlisted)",
    nonFunctionalRequirements: "- Read-heavy\n- Durable storage of text blobs\n- Low-latency reads",
    estimationNotes: "- 10M pastes/month, avg 10KB ≈ 100GB/month\n- Store text in object storage, metadata in DB",
    referenceSolution: "1. **Metadata** (key, expiry, owner) in a KV/SQL store; **blob** in object storage.\n2. **Key generation** like the URL shortener.\n3. **Reads** served from cache/CDN; large blobs streamed from object storage.\n4. **Expiry** via TTL + lazy/background cleanup.",
    commonPitfalls: "- Storing large blobs in the relational DB\n- No expiry/cleanup strategy",
    topics: ["Object Storage", "Caching", "CDN", "SQL vs NoSQL"],
    companies: ["Amazon", "Microsoft"],
  },
  {
    slug: "design-twitter-news-feed",
    title: "Design Twitter News Feed",
    difficulty: "hard",
    category: "Social/Feed",
    prompt: "Design the home timeline for a social network: users follow others and see a feed of recent posts.",
    functionalRequirements: "- Post a tweet\n- Follow/unfollow users\n- Home timeline of followees' recent posts\n- Optional: likes/retweets",
    nonFunctionalRequirements: "- Read-heavy; timeline must load fast (<200ms)\n- Eventually consistent feed is acceptable\n- Handle celebrity (high fan-out) users",
    estimationNotes: "- 300M DAU, 600M tweets/day ≈ 7K writes/s, ~700K timeline reads/s\n- Hot vs cold users skew heavily",
    referenceSolution: "1. **Fan-out on write (push)**: precompute each follower's timeline in a cache (Redis list) — fast reads, costly for celebrities.\n2. **Fan-out on read (pull)**: merge followees' tweets at read time — cheap writes, slower reads.\n3. **Hybrid**: push for normal users, pull-merge for celebrity followees.\n4. **Storage**: tweets in a sharded store; timelines in Redis; media in object storage + CDN.\n5. **Ranking**: start chronological; layer ML ranking later.",
    commonPitfalls: "- Pure push for celebrities (write amplification)\n- Ignoring the hybrid model\n- Not caching timelines",
    topics: ["Caching", "Database Sharding", "Pub/Sub", "Eventual vs Strong Consistency", "Message Queues"],
    companies: ["Facebook", "Google", "Bytedance"],
  },
  {
    slug: "design-instagram",
    title: "Design Instagram",
    difficulty: "hard",
    category: "Social/Feed",
    prompt: "Design a photo-sharing service: upload photos, follow users, and view a feed.",
    functionalRequirements: "- Upload/view photos\n- Follow users; feed of followees' photos\n- Likes and comments",
    nonFunctionalRequirements: "- Read-heavy; media-heavy\n- Highly available; low feed latency",
    estimationNotes: "- 500M DAU, 100M photos/day, avg 2MB ≈ 200TB/day media\n- Metadata writes ~1K/s",
    referenceSolution: "1. **Media**: upload to object storage via presigned URLs; serve through CDN; generate thumbnails async.\n2. **Metadata**: photo/user/follow graphs in sharded stores.\n3. **Feed**: hybrid fan-out like Twitter.\n4. **Async pipeline**: image processing via a queue.",
    commonPitfalls: "- Routing media bytes through app servers\n- Synchronous image processing\n- Not using a CDN",
    topics: ["Object Storage", "CDN", "Caching", "Database Sharding", "Message Queues"],
    companies: ["Facebook", "Google"],
  },
  {
    slug: "design-whatsapp",
    title: "Design WhatsApp / Messenger",
    difficulty: "hard",
    category: "Messaging",
    prompt: "Design a real-time 1:1 and group chat service with delivery/read receipts and offline delivery.",
    functionalRequirements: "- Send/receive messages in real time (1:1 and group)\n- Delivery + read receipts\n- Offline message delivery; online presence",
    nonFunctionalRequirements: "- Low latency real-time push\n- Durable until delivered; ordered per conversation\n- Massive concurrent connections",
    estimationNotes: "- 2B users, 100B messages/day ≈ 1.2M msgs/s\n- Millions of concurrent WebSocket connections",
    referenceSolution: "1. **Connection layer**: WebSocket gateway servers; a session registry maps user → connected gateway.\n2. **Routing**: messages flow through a queue/router to the recipient's gateway; store-and-forward when offline.\n3. **Storage**: per-conversation message store (sharded by conversation id), ordered by sequence number.\n4. **Receipts/presence**: lightweight events; presence via heartbeats + TTL.\n5. **Groups**: fan-out to members; large groups use a pull model.",
    commonPitfalls: "- Ignoring connection-to-server mapping\n- No ordering guarantee per conversation\n- Storing presence durably instead of TTL",
    topics: ["WebSockets vs Polling", "Message Queues", "Database Sharding", "Idempotency", "Backpressure"],
    companies: ["Facebook", "Bytedance", "Grab"],
  },
  {
    slug: "design-uber",
    title: "Design Uber / Ride-Hailing",
    difficulty: "hard",
    category: "Geo",
    prompt: "Design a ride-hailing service that matches riders with nearby drivers and tracks trips in real time.",
    functionalRequirements: "- Riders request rides; match to nearby drivers\n- Real-time driver location updates\n- Trip lifecycle + pricing/ETA",
    nonFunctionalRequirements: "- Low-latency matching\n- High write throughput (location pings)\n- Geo-partitioned, highly available",
    estimationNotes: "- 5M active drivers pinging every 4s ≈ 1.2M writes/s\n- Matching reads in busy cells",
    referenceSolution: "1. **Location ingestion**: drivers push location to a gateway → in-memory geo index (geohash/QuadTree) updated frequently.\n2. **Matching**: query the rider's geohash cell + neighbors for candidate drivers; rank by ETA.\n3. **Trip service**: state machine (requested → matched → ongoing → completed) backed by a durable store.\n4. **Geo-sharding**: partition by region/city.\n5. **Pricing/ETA**: separate services; surge from demand/supply per cell.",
    commonPitfalls: "- Storing high-frequency pings in a relational DB\n- Single global index instead of geo-sharding\n- Not handling cell-boundary matches",
    topics: ["Geohashing & QuadTree", "Caching", "Database Sharding", "Message Queues", "Load Balancing"],
    companies: ["Grab", "Amazon", "Bytedance"],
  },
  {
    slug: "design-youtube",
    title: "Design YouTube / Video Streaming",
    difficulty: "hard",
    category: "Streaming",
    prompt: "Design a service to upload, transcode, store, and stream videos at scale.",
    functionalRequirements: "- Upload videos; transcode to multiple resolutions\n- Stream with adaptive bitrate\n- View counts and recommendations (basic)",
    nonFunctionalRequirements: "- Massive read bandwidth; smooth playback\n- Durable storage of huge media\n- Global low-latency delivery",
    estimationNotes: "- 500 hours uploaded/min; petabytes of storage\n- Egress dominated by CDN",
    referenceSolution: "1. **Upload**: resumable upload to object storage; enqueue a transcoding job.\n2. **Transcoding pipeline**: workers produce HLS/DASH segments at multiple bitrates.\n3. **Delivery**: segments cached at the CDN edge; adaptive bitrate on the client.\n4. **Metadata**: video/user/view-count stores; view counts aggregated async.\n5. **Recommendations**: offline batch + online ranking (out of scope detail).",
    commonPitfalls: "- Synchronous transcoding\n- Serving video from origin instead of CDN\n- Counting views synchronously",
    topics: ["Object Storage", "CDN", "Message Queues", "Caching", "Backpressure"],
    companies: ["Google", "Netflix", "Amazon"],
  },
  {
    slug: "design-netflix",
    title: "Design Netflix Streaming",
    difficulty: "hard",
    category: "Streaming",
    prompt: "Design a VOD streaming platform focused on smooth playback and personalized catalogs.",
    functionalRequirements: "- Browse catalog; play titles with ABR\n- Resume playback across devices\n- Personalized rows",
    nonFunctionalRequirements: "- Very high availability; minimal rebuffering\n- Global delivery; pre-positioned content",
    estimationNotes: "- 200M+ subscribers; peak egress in Tbps\n- Catalog is mostly static and cacheable",
    referenceSolution: "1. **Pre-encode** titles into ABR ladders stored in object storage.\n2. **Open Connect-style CDN**: push popular content to edge/ISP caches ahead of demand.\n3. **Playback service** issues manifests + DRM-protected segment URLs.\n4. **Bookmarks** store last-watched position per user/title.\n5. **Personalization** served from precomputed recommendation stores.",
    commonPitfalls: "- Treating it as read-time transcoding\n- Ignoring proactive content placement at the edge",
    topics: ["CDN", "Object Storage", "Caching", "Eventual vs Strong Consistency"],
    companies: ["Netflix", "Amazon"],
  },
  {
    slug: "design-rate-limiter",
    title: "Design a Distributed Rate Limiter",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a rate limiter that throttles requests per user/API key across a fleet of servers.",
    functionalRequirements: "- Limit N requests per window per key\n- Work across many app servers\n- Return remaining quota / 429 on exceed",
    nonFunctionalRequirements: "- Very low added latency\n- Accurate enough; fail-open vs fail-closed decision",
    estimationNotes: "- Millions of keys; high QPS\n- Counter ops must be O(1)",
    referenceSolution: "1. **Algorithm**: token bucket (smooth, allows bursts) or sliding-window log/counter.\n2. **Shared state**: counters in Redis keyed by (key, window); atomic increments + TTL.\n3. **Local + global**: per-node token buckets synced to a central store to cut hot-key load.\n4. **Edge enforcement** at the API gateway.",
    commonPitfalls: "- Per-node counters that don't aggregate (limit × N)\n- Fixed-window boundary bursts\n- Not deciding fail-open vs fail-closed",
    topics: ["Rate Limiting", "Caching", "API Gateway", "Consistent Hashing"],
    companies: ["Amazon", "Google", "Microsoft"],
  },
  {
    slug: "design-web-crawler",
    title: "Design a Web Crawler",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a scalable crawler that fetches web pages for indexing while being polite and avoiding duplicates.",
    functionalRequirements: "- Fetch pages starting from seed URLs\n- Extract and enqueue new links\n- Respect robots.txt and politeness",
    nonFunctionalRequirements: "- Scalable to billions of pages\n- Avoid re-crawling duplicates\n- Distributed and fault tolerant",
    estimationNotes: "- 1B pages, avg 100KB ≈ 100TB raw\n- Crawl rate limited per-domain",
    referenceSolution: "1. **URL frontier**: priority + politeness queues partitioned by domain.\n2. **Fetchers**: distributed workers; per-domain rate limiting.\n3. **Dedup**: Bloom filter / hash set of seen URLs + content fingerprints.\n4. **Storage**: raw pages in object storage; link graph in a store; metadata in DB.\n5. **Robots/politeness** cached per domain.",
    commonPitfalls: "- No politeness/robots handling\n- Memory-heavy exact dedup instead of Bloom filters\n- Domain hot-spotting",
    topics: ["Bloom Filters", "Message Queues", "Object Storage", "Rate Limiting", "Consistent Hashing"],
    companies: ["Google", "Microsoft", "Amazon"],
  },
  {
    slug: "design-notification-system",
    title: "Design a Notification System",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a system that sends push, SMS, and email notifications reliably at scale.",
    functionalRequirements: "- Send notifications across channels (push/SMS/email)\n- Support templates and user preferences\n- Retries and delivery tracking",
    nonFunctionalRequirements: "- At-least-once delivery without duplicates\n- High throughput; provider failover",
    estimationNotes: "- 100M notifications/day ≈ 1.2K/s avg, bursty\n- Per-provider rate limits",
    referenceSolution: "1. **Ingestion API** → queue; a dispatcher fans out per channel.\n2. **Channel workers** call providers (APNs/FCM/Twilio/SES) with retries + dead-letter queues.\n3. **Idempotency keys** + dedupe to avoid double-sends.\n4. **Preferences/opt-out** checked before send; rate limiting per user.\n5. **Tracking** of sent/delivered/failed events.",
    commonPitfalls: "- No dedupe under at-least-once delivery\n- Ignoring provider rate limits/failover\n- Synchronous sends blocking the API",
    topics: ["Message Queues", "Idempotency", "Rate Limiting", "Pub/Sub", "Backpressure"],
    companies: ["Amazon", "Facebook", "Agoda"],
  },
  {
    slug: "design-dropbox",
    title: "Design Dropbox / Google Drive",
    difficulty: "hard",
    category: "Storage",
    prompt: "Design a file storage and sync service that keeps files consistent across a user's devices.",
    functionalRequirements: "- Upload/download files; sync across devices\n- File versioning and conflict handling\n- Sharing",
    nonFunctionalRequirements: "- Durable; efficient sync (only changed chunks)\n- Eventually consistent across devices",
    estimationNotes: "- Large files; dedup via chunking\n- Sync metadata writes dominate",
    referenceSolution: "1. **Chunking**: split files into content-addressed chunks; upload only changed chunks (dedup).\n2. **Metadata service**: file tree, versions, chunk lists in a DB.\n3. **Blob storage** for chunks; CDN for downloads.\n4. **Sync**: clients poll/subscribe to a change feed; resolve conflicts (last-writer-wins or versioned).\n5. **Notification** of changes via long-poll/WebSocket.",
    commonPitfalls: "- Re-uploading whole files\n- No conflict resolution strategy\n- Coupling metadata and blob stores",
    topics: ["Object Storage", "Change Data Capture", "Eventual vs Strong Consistency", "Caching", "WebSockets vs Polling"],
    companies: ["Amazon", "Google", "Microsoft"],
  },
  {
    slug: "design-ticketmaster",
    title: "Design Ticketmaster / Event Booking",
    difficulty: "medium",
    category: "Commerce",
    prompt: "Design a system to browse events and book seats without double-booking under high contention.",
    functionalRequirements: "- Browse events and available seats\n- Reserve and purchase seats\n- Hold seats temporarily during checkout",
    nonFunctionalRequirements: "- Strong consistency for seat allocation (no double-booking)\n- Handle flash-sale spikes",
    estimationNotes: "- Spiky load at on-sale time\n- Inventory contention on popular events",
    referenceSolution: "1. **Inventory** in a strongly consistent store; seats have states (available/held/booked).\n2. **Reservation**: atomic compare-and-set / row lock to hold a seat with a TTL; confirm on payment.\n3. **Queue/waiting room** to throttle flash-sale traffic.\n4. **Payment** via idempotent transaction; release expired holds.\n5. **Read replicas/cache** for browsing.",
    commonPitfalls: "- Eventual consistency on inventory (double-booking)\n- No hold expiry\n- Not throttling on-sale spikes",
    topics: ["Eventual vs Strong Consistency", "Idempotency", "Caching", "Rate Limiting", "Replication"],
    companies: ["Amazon", "Agoda", "Grab"],
  },
  {
    slug: "design-distributed-cache",
    title: "Design a Distributed Cache",
    difficulty: "hard",
    category: "Infra/Primitive",
    prompt: "Design a distributed in-memory cache (like Redis/Memcached cluster) with sharding and replication.",
    functionalRequirements: "- get/set/delete with TTL\n- Distribute keys across nodes\n- Tolerate node failures",
    nonFunctionalRequirements: "- Sub-ms latency; high throughput\n- Available under node loss; bounded staleness",
    estimationNotes: "- TBs of hot data across N nodes\n- Hot-key skew possible",
    referenceSolution: "1. **Partitioning**: consistent hashing with virtual nodes to spread keys and limit reshuffling.\n2. **Replication**: each shard has replicas for availability; async replication.\n3. **Eviction**: LRU/LFU; per-key TTL.\n4. **Client routing**: smart client or proxy maps key → node.\n5. **Hot keys**: replicate/duplicate; request coalescing to avoid stampedes.",
    commonPitfalls: "- Modulo hashing (mass reshuffle on resize)\n- Ignoring hot keys and cache stampede\n- No replication/failover",
    topics: ["Consistent Hashing", "Caching", "Replication", "Quorum & Consensus", "Bloom Filters"],
    companies: ["Amazon", "Google", "Microsoft"],
  },
  {
    slug: "design-search-autocomplete",
    title: "Design Search Autocomplete / Typeahead",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a typeahead service that suggests top completions as the user types.",
    functionalRequirements: "- Return top-k suggestions for a prefix\n- Rank by popularity/recency\n- Update suggestions from query logs",
    nonFunctionalRequirements: "- Very low latency (<50ms)\n- Eventually fresh suggestions are fine",
    estimationNotes: "- Billions of queries; heavy reads\n- Prefix space is large but cacheable",
    referenceSolution: "1. **Trie** of prefixes with precomputed top-k per node (stored in a fast KV/in-memory store).\n2. **Offline pipeline** aggregates query logs → rebuilds/updates the trie's top-k.\n3. **Serving**: cache hot prefixes at the edge; debounce on the client.\n4. **Sharding** the trie by prefix range.",
    commonPitfalls: "- Computing top-k at query time\n- No edge/cache for hot prefixes\n- Real-time updates instead of batch",
    topics: ["Indexing", "Caching", "Database Sharding", "CDN"],
    companies: ["Google", "Amazon", "Bytedance"],
  },
  {
    slug: "design-leaderboard",
    title: "Design a Real-Time Leaderboard",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a leaderboard that ranks millions of players by score with fast top-k and rank lookups.",
    functionalRequirements: "- Update a player's score\n- Get top-k\n- Get a player's rank",
    nonFunctionalRequirements: "- Low-latency reads/writes\n- Approximate ranks acceptable for huge boards",
    estimationNotes: "- 50M players; frequent score updates\n- Top-k reads dominate",
    referenceSolution: "1. **Sorted set** (Redis ZSET) for score → rank in O(log n).\n2. **Sharding** by game/region; merge for global views.\n3. **Approximate global rank** via per-shard percentiles for very large boards.\n4. **Durability**: periodic snapshots + a backing DB.",
    commonPitfalls: "- Scanning a table to compute rank\n- Single global ZSET hot-spot\n- No durability for in-memory state",
    topics: ["Caching", "Database Sharding", "Indexing", "Replication"],
    companies: ["Bytedance", "Amazon", "Grab"],
  },
  {
    slug: "design-payment-system",
    title: "Design a Payment System",
    difficulty: "hard",
    category: "Commerce",
    prompt: "Design a payment processing system handling charges, with correctness, idempotency, and reconciliation.",
    functionalRequirements: "- Charge/refund via payment providers\n- Idempotent transactions\n- Ledger + reconciliation",
    nonFunctionalRequirements: "- Strong consistency and exactly-once effect\n- Auditable; highly available",
    estimationNotes: "- Lower QPS but high correctness bar\n- Money must never be lost/duplicated",
    referenceSolution: "1. **Idempotency keys** on every charge to make retries safe.\n2. **Double-entry ledger** as the source of truth (append-only).\n3. **Provider integration** via a queue; handle async webhooks for final state.\n4. **Saga/state machine** for multi-step flows; compensating actions on failure.\n5. **Reconciliation** jobs compare ledger vs provider statements.",
    commonPitfalls: "- No idempotency (double charges)\n- Mutable balances instead of an immutable ledger\n- Ignoring webhook/async settlement",
    topics: ["Idempotency", "Quorum & Consensus", "Message Queues", "Eventual vs Strong Consistency", "Write-Ahead Log"],
    companies: ["Amazon", "Grab", "Agoda"],
  },
  {
    slug: "design-distributed-message-queue",
    title: "Design a Distributed Message Queue (Kafka)",
    difficulty: "hard",
    category: "Infra/Primitive",
    prompt: "Design a durable, partitioned pub/sub log like Kafka with ordered, replayable messages.",
    functionalRequirements: "- Produce/consume messages on topics\n- Ordering within a partition\n- Consumer groups; replay from offset",
    nonFunctionalRequirements: "- High throughput; durable\n- At-least-once (or exactly-once) delivery",
    estimationNotes: "- Millions of msgs/s; retention in TBs\n- Sequential disk I/O is key",
    referenceSolution: "1. **Topic = partitions**; each partition is an append-only log on disk (write-ahead log).\n2. **Ordering** guaranteed within a partition; key → partition via hashing.\n3. **Replication**: leader + follower replicas per partition; ISR + acks for durability.\n4. **Consumers** track offsets; consumer groups split partitions.\n5. **Leader election** via a coordinator (ZooKeeper/KRaft).",
    commonPitfalls: "- Promising global ordering across partitions\n- Random I/O instead of sequential append\n- No replication/ISR for durability",
    topics: ["Write-Ahead Log", "Replication", "Pub/Sub", "Leader Election", "Quorum & Consensus"],
    companies: ["Amazon", "Netflix", "Bytedance"],
  },
  {
    slug: "design-job-scheduler",
    title: "Design a Distributed Job Scheduler",
    difficulty: "medium",
    category: "Infra/Primitive",
    prompt: "Design a system to schedule and run jobs (cron/one-off) reliably across a worker fleet.",
    functionalRequirements: "- Schedule recurring and one-off jobs\n- Execute exactly/at-least once\n- Retries and visibility",
    nonFunctionalRequirements: "- Reliable; no missed or duplicate runs\n- Scales to many jobs/workers",
    estimationNotes: "- Millions of scheduled jobs\n- Time-bucketed lookups",
    referenceSolution: "1. **Schedule store** keyed by next-run time (time-bucketed index).\n2. **Dispatcher** polls due jobs → enqueues to a work queue; uses leader election to avoid duplicates.\n3. **Workers** pull from the queue; idempotency keys make retries safe.\n4. **Visibility timeout** + dead-letter for stuck jobs.\n5. **State machine** per job run.",
    commonPitfalls: "- Multiple dispatchers double-enqueuing (no leader election)\n- No idempotency for retries\n- Scanning all jobs instead of time-bucketing",
    topics: ["Message Queues", "Leader Election", "Idempotency", "Database Sharding", "Backpressure"],
    companies: ["Amazon", "Microsoft", "Google"],
  },
  {
    slug: "design-key-value-store",
    title: "Design a Distributed Key-Value Store (DynamoDB)",
    difficulty: "hard",
    category: "Storage",
    prompt: "Design a highly available, partitioned key-value store with tunable consistency.",
    functionalRequirements: "- get/put by key\n- Horizontal scale; replication\n- Tunable consistency",
    nonFunctionalRequirements: "- Always writable (AP-leaning)\n- Bounded staleness; fault tolerant",
    estimationNotes: "- PBs across thousands of nodes\n- Hot-partition avoidance",
    referenceSolution: "1. **Partitioning**: consistent hashing ring with virtual nodes.\n2. **Replication**: N replicas; quorum reads/writes (R+W>N) for tunable consistency.\n3. **Conflict resolution**: vector clocks / last-writer-wins; hinted handoff for temporary failures.\n4. **Anti-entropy**: Merkle trees to sync replicas.\n5. **Membership/failure detection** via gossip.",
    commonPitfalls: "- Ignoring quorum math (R+W>N)\n- No conflict resolution for concurrent writes\n- Modulo hashing",
    topics: ["Consistent Hashing", "Replication", "Quorum & Consensus", "Eventual vs Strong Consistency", "Bloom Filters"],
    companies: ["Amazon", "Google", "Microsoft"],
  },
  {
    slug: "design-proximity-service",
    title: "Design a Proximity Service (Yelp / Nearby)",
    difficulty: "hard",
    category: "Geo",
    prompt: "Design a service that returns businesses/points-of-interest near a user's location.",
    functionalRequirements: "- Find places within radius / nearby\n- Filter by category\n- Add/update places",
    nonFunctionalRequirements: "- Low-latency geo queries\n- Read-heavy; mostly static data",
    estimationNotes: "- 200M places; heavy read QPS\n- Spatial index needed",
    referenceSolution: "1. **Spatial index**: geohash or QuadTree to bucket places by cell.\n2. **Query**: compute the user's cell + neighbors; fetch candidates; filter by exact distance.\n3. **Storage**: places in a DB; precomputed geo index in a fast store/cache.\n4. **Sharding** by geo region; cache hot cities.",
    commonPitfalls: "- Full-table scans with distance math\n- One global index instead of geo-sharding\n- Missing cell-boundary results",
    topics: ["Geohashing & QuadTree", "Indexing", "Caching", "Database Sharding"],
    companies: ["Grab", "Agoda", "Google"],
  },
  {
    slug: "design-ad-click-aggregator",
    title: "Design an Ad Click Aggregator",
    difficulty: "hard",
    category: "Streaming",
    prompt: "Design a system to ingest ad-click events and produce near-real-time aggregated metrics.",
    functionalRequirements: "- Ingest high-volume click events\n- Aggregate counts by ad/time window\n- Serve dashboards + handle late/duplicate events",
    nonFunctionalRequirements: "- High write throughput; near-real-time\n- Accurate (dedupe, exactly-once-ish)",
    estimationNotes: "- 1M clicks/s peak\n- Aggregations over minute/hour windows",
    referenceSolution: "1. **Ingestion** into a partitioned log (Kafka) for buffering + replay.\n2. **Stream processing** (Flink/Spark) with windowed aggregation; watermarks for late events.\n3. **Dedup** via idempotency keys / event ids.\n4. **Serving store**: pre-aggregated OLAP/time-series store for dashboards.\n5. **Lambda/Kappa**: batch recompute for correctness.",
    commonPitfalls: "- Writing each click straight to the DB\n- Ignoring late/duplicate events\n- No windowing/watermarks",
    topics: ["Pub/Sub", "Change Data Capture", "Idempotency", "Backpressure", "Write-Ahead Log"],
    companies: ["Google", "Facebook", "Bytedance"],
  },
  {
    slug: "design-object-storage",
    title: "Design an Object Storage Service (S3)",
    difficulty: "hard",
    category: "Storage",
    prompt: "Design a durable, highly available blob store for arbitrarily large objects.",
    functionalRequirements: "- put/get/delete objects in buckets\n- Large object (multipart) uploads\n- Strong durability; metadata listing",
    nonFunctionalRequirements: "- 11 9s durability; high availability\n- Scales to exabytes",
    estimationNotes: "- Exabyte scale; huge objects\n- Metadata index is the scaling challenge",
    referenceSolution: "1. **Data plane**: split objects into chunks; store with replication or erasure coding across nodes/zones.\n2. **Metadata service**: bucket/object → chunk locations (sharded, replicated).\n3. **Multipart upload**: parallel chunk uploads + presigned URLs.\n4. **Durability**: erasure coding + cross-AZ placement; background repair via checksums.\n5. **Read path**: CDN for hot objects.",
    commonPitfalls: "- Replicating everything 3x instead of erasure coding at scale\n- Metadata as a single DB bottleneck\n- Routing bytes through app tier",
    topics: ["Object Storage", "Replication", "Consistent Hashing", "CDN", "Quorum & Consensus"],
    companies: ["Amazon", "Microsoft", "Google"],
  },
];
